# Generated by Django 5.2.5 on 2025-09-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
