# Generated by Django 5.2.5 on 2025-09-21 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_media_type_message_media_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
    ]
