# Generated by Django 5.2.5 on 2025-09-22 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options'),
        ('match', '0003_block_match_block_blocker_cae043_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['match', 'created_at'], name='chat_messag_match_i_882f71_idx'),
        ),
    ]
