# Generated by Django 5.2.5 on 2025-11-02 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestyleChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_choice', models.CharField(blank=True, choices=[('never', 'never'), ('socially', 'socially'), ('occasionally', 'occasionally'), ('often', 'often')], max_length=20, null=True)),
                ('smoke_choice', models.CharField(blank=True, choices=[('never', 'never'), ('socially', 'socially'), ('occasionally', 'occasionally'), ('often', 'often')], max_length=30, null=True)),
                ('active_choice', models.CharField(blank=True, choices=[('not_really', 'not_really'), ('sometimes', 'sometimes'), ('regularly', 'regularly'), ('fitness_is_life', 'fitness_is_life')], max_length=30, null=True)),
                ('diet_choice', models.CharField(blank=True, choices=[('no_preference', 'no_preference'), ('veg', 'veg'), ('non_veg', 'non_veg'), ('other', 'other')], max_length=30, null=True)),
                ('travel_choice', models.CharField(blank=True, choices=[('homebody', 'homebody'), ('sometimes', 'sometimes'), ('love_exploring', 'love_exploring'), ('always_planning', 'always_planning')], max_length=30, null=True)),
                ('pet_choice', models.CharField(blank=True, choices=[('love_pets', 'love_pets'), ('okay_with_pets', 'okay_with_pets'), ('prefer_no_pets', 'prefer_no_pets')], max_length=30, null=True)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles_with_lifestyle', to='user.profile')),
            ],
        ),
    ]
