# Generated by Django 5.2.5 on 2025-08-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_interest_rename_about_profile_bio_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intention',
            field=models.CharField(blank=True, choices=[('friendship', 'friendship'), ('dating_only', 'dating_only'), ('marriage', 'marriage')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles', to='user.interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexual_orientation',
            field=models.CharField(blank=True, choices=[('gay', 'gay'), ('lesbian', 'lesbian'), ('bisexual', 'bisexual'), ('asexual', 'asexual'), ('demisexual', 'demisexual'), ('pansexual', 'pansexual'), ('queer', 'queer'), ('questioning', 'questioning')], max_length=20, null=True),
        ),
    ]
