# Generated by Django 5.2.5 on 2025-11-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_lifestylechoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_verified',
        ),
    ]
