# Generated by Django 5.2.5 on 2025-08-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_image_photo_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sexual_orientation',
            field=models.CharField(blank=True, choices=[('straight', 'straight'), ('gay', 'gay'), ('lesbian', 'lesbian'), ('bisexual', 'bisexual'), ('asexual', 'asexual'), ('demisexual', 'demisexual'), ('pansexual', 'pansexual'), ('queer', 'queer'), ('questioning', 'questioning')], max_length=20, null=True),
        ),
    ]
