# Generated by Django 5.2.5 on 2025-11-05 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_myuser_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
