# Generated by Django 5.2.5 on 2025-11-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_first_name_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interested_in',
            field=models.CharField(blank=True, choices=[('man', 'man'), ('woman', 'woman'), ('all', 'all')], max_length=10, null=True),
        ),
    ]
