# Generated by Django 5.2.5 on 2025-11-05 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_interested_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='looking_for',
        ),
    ]
