# Generated by Django 5.2.5 on 2025-11-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profile_looking_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relationship',
            field=models.CharField(blank=True, choices=[('serious_relationship', 'serious_relationship'), ('short_term_relationship', 'short_term_relationship'), ('friendship', 'friendship'), ('short_term_fun', 'short_term_fun'), ('text', 'text'), ('still_figuring_out', 'still_figuring_out')], max_length=100, null=True),
        ),
    ]
