# Generated by Django 5.2.5 on 2025-11-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='intention',
        ),
    ]
