# Generated by Django 5.2.5 on 2025-09-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_myuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestyleChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='show_orientation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_zodiac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='zodiac_sign',
            field=models.CharField(blank=True, choices=[('aries', 'aries'), ('taurus', 'taurus'), ('gemini', 'gemini'), ('cancer', 'cancer'), ('leo', 'leo'), ('virgo', 'virgo'), ('libra', 'libra'), ('scorpio', 'scorpio'), ('sagittarius', 'sagittarius'), ('capricorn', 'capricorn'), ('aquarius', 'aquarius'), ('pisces', 'pisces')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='user.interest'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifestyle_choices',
            field=models.ManyToManyField(related_name='profiles_with_lifestyle', to='user.lifestylechoices'),
        ),
    ]
