# Generated by Django 5.2.5 on 2025-11-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_profile_intention'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='predefined',
            field=models.BooleanField(default=False),
        ),
    ]
