# Generated by Django 5.2.5 on 2025-09-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_lifestylechoices_profile_show_orientation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LifestyleChoices',
            new_name='LifestyleChoice',
        ),
    ]
