# Generated by Django 5.2.5 on 2025-11-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_hobby_remove_profile_interests_profile_hobbies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(blank=True, choices=[('facebook', 'facebook'), ('instagram', 'instagram'), ('twitter', 'twitter'), ('linkedin', 'linkedin'), ('snapchat', 'snapchat'), ('tiktok', 'tiktok'), ('other', 'other')], max_length=20, null=True),
        ),
    ]
