# Generated by Django 5.2.5 on 2025-09-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_sociallink'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['latitude', 'longitude'], name='user_profil_latitud_17be64_idx'),
        ),
    ]
