# Generated by Django 5.2.5 on 2025-11-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='swipe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
