# Generated by Django 5.2.5 on 2025-09-22 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_block'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocker'], name='match_block_blocker_cae043_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user1'], name='match_match_user1_i_48376a_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user2'], name='match_match_user2_i_a1d9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['created_at'], name='match_match_created_b51748_idx'),
        ),
    ]
